- gatsby-node.js
- src/templates/Challenges/backend/Show.js
- src/templates/Challenges/project/Tool-Panel.js
- src/templates/Challenges/redux/execute-challenge-epic.js
- src/templates/Challenges/redux/index.js
- src/templates/Challenges/utils/build.js
- src/templates/Challenges/utils/fetch-and-cache.js
- utils/challengeTypes.js
> Add backend tests

- gatsby-config.js
- package.json
- yarn.lock
> Add site map plugin

- src/components/Map/map.css
> Fix carets in the map shrink issue #25

- package.json
- src/auth/index.js
- src/templates/Challenges/classic/Editor.js
- src/templates/Challenges/classic/Show.js
- src/templates/Challenges/components/CompletionModal.js
- src/templates/Challenges/components/ResetModal.js
- src/templates/Challenges/components/Side-Panel.js
- src/templates/Challenges/components/Tool-Panel.js
- src/templates/Challenges/redux/code-storage-epic.js
- src/templates/Challenges/redux/create-question-epic.js
- src/templates/Challenges/redux/index.js
- yarn.lock
> Feat:  Add code storage and lesson reset modal 

- src/templates/Challenges/backend/Show.js
- src/templates/Challenges/project/ProjectForm.js
- src/templates/Challenges/project/Show.js
- src/templates/Challenges/project/Tool-Panel.js
> All challenge views use CompletionModal

- gatsby-node.js
- src/introductions/apis-and-microservices/index.md
- src/introductions/data-visualization/index.md
- src/introductions/front-end-libraries/index.md
- src/introductions/information-security-and-quality-assurance/index.md
- src/introductions/javascript-algorithms-and-data-structures/index.md
- src/introductions/responsive-web-design/index.md
- src/templates/Introduction/SuperBlockIntro.js
- utils/gatsby/index.js
Please do not merge this. It is work in progress.
@Bouncey If I understood the first requirement correct for issue #30 then this should complete that requirement.
> Add superBlock intro pages

- src/components/Map/components/Block.js
- src/components/Map/components/Block.test.js
- src/components/Map/components/__snapshots__/Block.test.js.snap
- src/components/MapModal/index.js
- src/templates/Introduction/SuperBlockIntro.js
> Fix: map modal

- src/templates/Challenges/components/test-suite.css
Fixes issue in #51 where test results overlap
Closes #51
> remove .test-result height limitation to fix overlap issue

- CONTRIBUTING.md
> Fix remaining typo in branch creation step

- src/templates/Challenges/redux/execute-challenge-epic.js
> Update preview on mount

- src/templates/Introduction/Intro.js
> Add map button to intro pages

- src/__mocks__/intro-nodes.js
- src/components/Map/Map.js
- src/components/Map/Map.test.js
- src/components/Map/__snapshots__/Map.test.js.snap
- src/components/Map/components/Block.js
- src/components/Map/components/Block.test.js
- src/components/Map/components/SuperBlock.js
- src/components/Map/components/SuperBlock.test.js
- src/components/Map/components/__snapshots__/Block.test.js.snap
- src/components/Map/components/__snapshots__/SuperBlock.test.js.snap
- src/components/MapModal/index.js
- src/layouts/index.js
- src/templates/Introduction/intro.css
> Add intro pages to map

- src/templates/Challenges/utils/frame.js
Closes #78 
Closes #79 
I updated the version of react the main app uses, but forgot to update the adapter for challenge tests.
> Update enzyme adapter for react tests

- src/components/Map/map.css
- src/components/MapModal/index.js
- src/layouts/global.css
- src/pages/index.js
- src/templates/Challenges/classic/Show.js
- src/templates/Challenges/components/Side-Panel.js
- src/templates/Challenges/components/Tool-Panel.js
- src/templates/Challenges/components/tool-panel.css
- src/templates/Challenges/project/Tool-Panel.js
- src/templates/Introduction/Intro.js
> Fix: Map UI & Tool panel styles

- src/templates/Challenges/classic/Editor.js
Changed editor theme from `vs-dark` to `vs`.
But please tell me there'll be dark mode or I'll learn from a fork!
~Threat~ Joke aside, thank you for making it way easier to setup and contribute to 👏 
Closes #89
> Change editor theme

- src/templates/Introduction/intro.css
increase spacing between challenges in lists.
closes #91
> fix: increase spacing in challenge list

- src/redux/app/index.js
- src/templates/Challenges/redux/current-challenge-epic.js
- src/templates/Challenges/redux/index.js
> Update users currentChallengeId when on a new challenge

- gatsby-node.js
- sample.env
- src/redux/app/fetch-user-epic.js
- src/redux/app/hard-go-to-epic.js
- src/redux/app/index.js
- src/redux/store.js
> Redirect non-emailVerified users to www

- src/introductions/responsive-web-design/basic-html-and-html5/index.md
I first noticed a typo: **paragragh** should have been **paragraph**.
Then I read the rest to make sure there wasn't another typo and found a phrase that did not make sense so I slightly rewrote it.
> Typo and rewrote phrase about hypertext links

- src/redux/app/index.js
Fixes blank page after completing a new challenge as a signed in user and clicking on the curriculum link
Closes #140
> fix(typo): Fixes typo the made the local completedChallenges array unuseable

- src/introductions/front-end-libraries/react/index.md
> write up for React intro stub

- src/templates/Challenges/classic/Show.js
- src/templates/Challenges/components/Challenge-Title.js
- src/templates/Challenges/components/Side-Panel.js
> Challenge SidePanel tweaking

- src/introductions/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/index.md
I thought it will be cool to have a message with this 'keep going' attitude push forward into the challenges introduction, I'll update the others as well
> Updated index.md

- src/introductions/javascript-algorithms-and-data-structures/basic-javascript/index.md
Resolves https://github.com/freeCodeCamp/freeCodeCamp/issues/17520
I fixed the spelling of "arithemtic" to "arithmetic"
Also, I found a misplaced modifier in "basic programming concepts in JavaScript, which range"
The word "concepts" needs the modifier: "which" 
before fix:
after fix:
> fixing grammatical and spelling errors in javascript intro

- src/head/index.js
- src/templates/Challenges/components/Side-Panel.js
Closes  #185 
Closes freeCodeCamp/freeCodeCamp#17647
Closes freeCodeCamp/freeCodeCamp#17633
Closes freeCodeCamp/freeCodeCamp#17641
Closes freeCodeCamp/freeCodeCamp#17620
> Temp: Remove MathJax

- src/introductions/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md
I have added descriptions in this section will help other campers to understand the algorithms and help them solving problems. As this is my first pull request I will really appreciate any feedback or  advice. Thanks
> Description for Basic Algorithm Scripting

- package.json
- yarn.lock
Closes https://github.com/freeCodeCamp/curriculum/issues/16
Closes https://github.com/freeCodeCamp/learn/pull/188
> chore(seed): update curriculum to latest

- CONTRIBUTING.md
fixed a small typo in the numbered instructions on the instruction list (from 1 2 3 4 6 7 8 9 to 1 2 3 4 5 6 7 8)
> fix(contributing.md): fixed a typo in the instruction list

- src/introductions/front-end-libraries/redux/index.md
Followed the link from FCC to try and add a little more detail. Used intro from React read me.
> improved Redux intro

- src/templates/Challenges/classic/Editor.js
The code editor will auto focus when you complete a challenge and move to next one closes #192
> The code editor will auto focus when you complete a challenge

- src/components/Header/index.js
- src/components/Map/map.css
- src/layouts/global.css
- src/layouts/index.js
- src/layouts/layout.css
night mode styles for learn.freecodecamp.org
Closes #184
> updating styles for night-mode

- src/templates/Challenges/classic/Editor.js
> fix(editor): update night mode styles for the editor

- src/introductions/front-end-libraries/react-and-redux/index.md
Updated the stub for this series of challenges.
> Introduction to React Redux Challenges

- src/templates/Challenges/redux/create-question-epic.js
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17817
> fix(help): add param for correct category

- src/introductions/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md
ISSUES CLOSED: [#17970](
https://github.com/freeCodeCamp/freeCodeCamp/issues/17970)
Typo error in introduction to Basic Algorithm Scripting.
> fix(challenges): typo error

- src/introductions/front-end-libraries/react/index.md
As suggested by @KoniKodes, I changed the "a" to "an"  in the first sentence to correct the grammatical error.  Also, removed the "with JSX," and from the second sentence and started the sentence with "It".
> Corrected grammar mistake and made small wording change

- src/head/index.js
- src/head/sassjs.js
- src/templates/Challenges/rechallenge/transformers.js
have made: Sass compiling before tests run #216
> fix: Sass has not been compiled when tests running

- src/components/Header/header.css
- src/components/Map/map.css
> fix(styles): Fix styles for day mode and signed in avatar

- src/templates/Challenges/redux/execute-challenge-epic.js
- src/templates/Challenges/utils/frame.js
Addresses #291
@randelldawson @ojeytonwilliams for visability
> Fix challenge tests that rely on`console.log`

- package.json
- src/redux/propTypes.js
- src/templates/Challenges/classic/Show.js
- src/templates/Challenges/components/Side-Panel.js
- src/templates/Challenges/components/Tool-Panel.js
- src/templates/Challenges/components/VideoModal.js
- src/templates/Challenges/components/video-modal.css
- src/templates/Challenges/redux/index.js
- yarn.lock
New feature that was requested.
> Add 'watch a video' button and video modal.

- src/introductions/apis-and-microservices/apis-and-microservices-projects/index.md
Added a Readme for the introduction to the APIs and Micro services projects to give a base introduction to the projects and learnings on APIs
> Added a readme to Introduction to the API and microservices projects

- src/introductions/data-visualization/data-visualization-projects/index.md
Added details to the data visualization challenges
> Introduction to Data Visualization Challenges

- src/templates/Challenges/classic/Editor.js
> fix:modifying js code themes

- .gitignore
Add environment specific files to .gitignore file
> fix(.gitignore) add environment specific files to .gitignore

- package.json
- yarn.lock
Changed the stub Introduction page to an improved documented and understandable Introduction page.
> Changed the stub introduction page

- package.json
- src/components/Donation/Donation.js
- src/components/Donation/components/CardForm.js
- src/components/Donation/components/DonateForm.js
- src/components/Donation/donation.css
- yarn.lock
Client side implementation for https://github.com/freeCodeCamp/freeCodeCamp/pull/35677
> feat: add invisible Google reCAPTCHA

- src/templates/Challenges/redux/create-question-epic.js
As per https://github.com/freeCodeCamp/freeCodeCamp/pull/35917
> Swap out raw HTML syntax for semantic/idiomatic markdown
