src/templates/Challenges/classic/Show.js, src/templates/Challenges/project/Show.js
Made use of existing (unused) `randomCompliment()` from `src/templates/utils/get-words.js` to generate random compliment.
Implemented updates into `componentDidMount` and `componentDidUpdate` for the `ShowClassic` and `Project` components using existing `updateSuccessMessage` action.
Closes #35
=> fix: successMessage not changing

CONTRIBUTING.md
Fix for https://github.com/freeCodeCamp/learn/issues/44
=> Fix typo, add instruction to copy .env in CONTRIBUTING.md

src/templates/Challenges/classic/classic.css
Closes #52
- Change menu color (contrast ratio 6.58, meets minimum [accessibility guideline](https://developers.google.com/web/fundamentals/accessibility/accessible-styles#color_and_contrast))
- Add slight letter-spacing to make small text more legible
=> Fix editor menu color

src/templates/Challenges/rechallenge/transformers.js, src/templates/Challenges/redux/completion-epic.js, src/templates/Challenges/redux/execute-challenge-epic.js, src/templates/Challenges/redux/index.js, src/templates/Challenges/utils/build.js
These changes will print out babel errors to the console and will help to not crash the app when bad/unfinished code is in the editor.
=> Fix: Babel errors in the browser console for user code

src/templates/Challenges/classic/Show.js, src/templates/Challenges/classic/classic.css, src/templates/Challenges/components/Output.js, src/templates/Challenges/components/Preview.js, src/templates/Challenges/components/preview.css
Added a state to Show.js to track when the panes are being resized and passed said state to Preview.js as a prop. There I used state changes to toggle whether pointer events are set to auto or none. Seems like this was the easiest way to get Firefox to resize the panes the way Chrome does when the mouse moves over an iframe. 
Thought about using the propagateDimensions, renderOnResize, and renderOnResizeRate properties like with the editor here, but was unsure if that would cause the whole Preview component, including whatever is in the iframe, to be re-rendered, rather than just toggling the class. Similarly, I might try to go back and use the props method used here to rework the way the editor is resized if performance with lots of code might become an issue.
Removed the overflow: …
=> Fix Firefox Pane Resizing

src/components/Map/components/Block.js, src/components/Map/components/__snapshots__/Block.test.js.snap, src/components/Map/map.css, src/templates/Challenges/classic/Show.js, src/templates/Challenges/components/Preview.js, src/templates/Challenges/components/icons/GreenNotCompleted.js, src/templates/Challenges/components/test-suite.css
Fixes issue #103 
Note that I also changed the width of the `<GreenPass>` component. The width was 50px but the svg is only 15px. This was creating margins within the SVG, and they don't belong there. Margins should be set by any containing component. The only other place `<GreenPass>` is used is in the completion modal and I tested that to make sure my change didn't affect it.
=> fix: curriculum completion checkmark styling

src/introductions/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/index.md
Problem: Get 404'd when accessing https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai
Reason: The `index.md` was missing some words and mismatched with the url, causing 404.
The issue was raised on the main repo: https://github.com/freeCodeCamp/freeCodeCamp/issues/17298
=> Fix: 'Testing with Chai' 404 error

src/components/Header/index.js
closes [freeCodeCamp/freeCodeCamp#17533](https://github.com/freeCodeCamp/freeCodeCamp/issues/17533) and #177 
Whenever someone clicked on the logo they were taken to the curriculum page, so I have linked it to home page(https://www.freecodecamp.org).
=> changed logo link to home page

src/templates/Challenges/classic/Editor.js, src/templates/Challenges/classic/classic.css, src/templates/Challenges/components/Output.js
- Removed horizontal scrollbars: Closes #131
- Removed unnecessary vertical ones, too: Closes Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17415 (This fix is only for Chrome and Firefox as I'm unsure whether or not we support Safari. I'll try and submit a follow up PR for it if requested.)
- Fixed the editor's scrollbar issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/17293
---
---
All of the scrollbars in the first screenshot belong to the `ReflexElement` components. Something was off with the height and width of these components, causing the scrollbars to appear. I spent 2 hours inspecting them but couldn't figure out.
I decided to remove them all by applying `overflow: hidden` to the `.reflex-element` class. The results of this:
- Made the instruction pane …
=> Fix scrollbar issues

src/head/index.js, src/head/mathjax.js, src/templates/Challenges/components/Side-Panel.js, src/templates/Challenges/components/side-panel.css
Added a script tag to the header of the page in src/head/index.js via src/head/mathjax.js. Modified Side-Panel.js so that mathematical functions are rendered properly in the Rosetta Code problems. Had to use the CDN because I couldn't get the NPM package working, and a local package like the one used in Arcade Mode would be ignored if put into the public folder. We could probably use that local package if there's a better place to store it.
Since MathJax is set up currently to interpret anything between $...$ or $$...$$ as a math function, we will need to check some of the other problems that use those symbols on the same line.
=> Add MathJax

static/json/cats.json
Closes #17395
At least 5 challenges in `JSON APIs and Ajax` section depend upon this cats.json file. I have added the `cats.json` file in `/static/json` folder. Now the relative route `/json/cats.json` will correctly serve the `cats.json` file.
Please take look and see if this is the correct way to solve this issue.
.
=> fix: add cats json for seeding challenges

src/components/Map/map.css, src/pages/index.css
For mobile browser view I added some padding to the curriculum page and centered the list of challenges as well.
Closes [#156](https://github.com/freeCodeCamp/learn/issues/156)
=> Fixed: Added styles for mobile

src/templates/Challenges/classic/Show.js, utils/decodeHTMLEntities.js
WIP, please do not merge yet.
@Bouncey this is a first attempt at fixing issue #53. It does decode HTML entities as requested.
Unfortunately there seems to be another bug with the console output. Here is the new output. Note the "\<wbr\>" string in the link on the 2nd line:
```
// running test
Your a element should have the anchor text of "cat photos".
You need an a element that links to http://freecatphotoapp<wbr>.com
Make sure your a element has a closing tag.
// tests completed
```
For reference, here is the test message text:
```
You need an <code>a</code> element that links to <code>http://freecatphotoapp<wbr>.com</code>
```
As you can see, somewhere the HTML elements are getting stripped out, but it looks like it is choking on "\<wbr\>" element for some reason.
If you can point me …
=> WIP: decodeHTMLEntities

src/templates/Challenges/classic/Show.js
Close #152 
The change hides and shows the splitter (between the editors and the preview pane) based on the preview pane's presence.
At first, I nested the splitter and the preview pane inside a `<Fragment>` under a single conditional but it didn't work. When the splitter is clicked, it threw an error `this.props.events is undefined`, so I thought the props weren't passed to the splitter somehow. However, splitting them up into two separate conditionals did the job.
I later found that Bouncey did wrap the splitter in a conditional, and got this issue too (https://github.com/leefsmp/Re-Flex/issues/47), but I'm not sure why he decided to put the splitter back out ¯\\\_(ツ)_/¯
The Reflex author also suggested using two conditionals, because
>In the current version only ReflexElement and …
=> Fix: render ReflexSplitter conditionally

src/templates/Challenges/project/ProjectForm.js
A fix for issue 67. Keydown and keyup event listeners added to determine when enter and ctrl are pressed down. 'If' statement added to the handleSubmit function to check these two keys are pressed before submitting. This statement also covers the case that enter is not pressed and so the mouse must have been clicked to submit the form.
Additionally, the handleSubmit function was changed from an arrow function to match the formatting of the other functions.
Tested on my machine (Windows 7, Firefox Quantum 64-bit).
=> Fix for ctrl key having no impact on submit process

src/components/Header/index.js, src/head/mathjax.js, src/templates/Challenges/backend/Show.js, src/templates/Challenges/classic/Show.js, src/templates/Challenges/components/Output.js, src/templates/Challenges/project/ProjectForm.js, src/templates/Challenges/project/Show.js, src/templates/Challenges/utils/index.js
Do not merge until the corresponding guide PR has been merged.
Depends on freecodecamp/guide#8217
=> Fix: Hint Button

src/layouts/global.css
This PR fixes #209.
I have added following code in the `global.css` file
```css
.night .intro-toc a {
color: #006400;
}
```
Here is the screenshot of upcoming lessons after the change:
Please take a look.
=> fix(theme): upcoming lessons readability in night mode

src/layouts/layout.css
adding 100vh property to layout.css in order to make the background color fill the browser window
Closes #203
=> fix(layout): night mode background color now fits full screen

src/layouts/global.css
A couple of tweaks to night mode
- Allows the ability to see the selection of text in the editor:
Before
After
- Make the test result odd rows darker:
Before
After
Fixes partially [freeCodeCamp/freeCodeCamp/#17782](https://github.com/freeCodeCamp/freeCodeCamp/issues/17782)
=> fix: night mode tweaks

src/templates/Challenges/utils/frame.js
Issue freeCodeCamp/freeCodeCamp#17791
=> Misspelling: "onNext" is called instead of "next" on an Observable

src/templates/Challenges/components/Test-Suite.js, src/templates/Challenges/components/icons/GreenNotCompleted.js, src/templates/Challenges/components/icons/GreenPass.js
- Added `sr-text` to report challenges' completion state.
- Removed `<code>` tag from test suite text for screen readers.
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17731
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17777
Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17775
=> Fix: Accessibility issues

src/layouts/global.css
Hi, I added a dark background of the quote container so that it will be visible in Night Mode. Also, I added the color of the curriculum button to stay as is in Night Mode.
Closes #237
=> Fix: 404 page quote in Night Mode

src/templates/Challenges/utils/build.js
I added the new CDN that @raisedadead suggested in [#155](https://github.com/freeCodeCamp/learn/issues/155)
Closes [#155](https://github.com/freeCodeCamp/learn/issues/155)
=> Fix: Removed old jquery CDN and added a more accessible CDN

src/templates/Challenges/rechallenge/transformers.js, src/templates/Challenges/redux/code-lock-epic.js, src/templates/Challenges/redux/execute-challenge-epic.js, src/templates/Challenges/redux/index.js
I expect to see a preview while a challenge is edited, and it is so in HTML/CSS/SASS challenges. But in JS/React challenges most of the time a preview not working.
Now preview is disabled on syntax errors in the editor and will be enabled only after press "Run tests".
The PR is correcting this behavior.
=> fix: on error preview is disabled 

src/components/Map/map.css
I added 3 lines of styles which, in my opinion, make the curriculum list a lot cleaner and separated per track. I've attached before and after screenshots so that you see what I mean (they are kinda tall):
--- After
--- After
--- Before
--- Before
=> Added a few styles to increase heirarchy of curriculum list

src/head/index.js, src/html.js, src/templates/Challenges/classic/Show.js, src/templates/Challenges/components/Challenge-Description.js, src/templates/Challenges/components/Side-Panel.js
Did some retooling and was able to disable MathJax for the entire page from a top-level div by adding the class name tex2jax_ignore. Brought the dasherize function into Show.js and used it to pass a new prop section down through Side-Panel.js into Challenge-Description.js to add a section class name to each of the challenge-instructions divs. Then was able to use the `$...$` delimiters that caused problems before, but only for the Rosetta Code challenges.
=> fix: reenable mathjax for rosetta code

src/templates/Challenges/utils/frame.js
Removed the base tag from the header of the preview iframe. The href and target attributes were causing links within the iframe to open a new tab and would point to /, which created problems with some challenges where users should link to other in-page elements like a footer.
Closes: https://github.com/freeCodeCamp/freeCodeCamp/issues/17713
=> fix: In-page anchor links in iframe

src/templates/Challenges/redux/execute-challenge-epic.js, src/templates/Challenges/redux/index.js, src/templates/Challenges/utils/frame.js
To implement @ktajpuri's suggestion I gave the editor logs their own actions.  This allowed me to suppress the '// console output' message if there are no log and postpone their output until the tests are complete.
Closes #189
=> Added reporting of console.log from editor. Refactored a little.

src/components/Header/header.css, src/components/Header/index.js
Attempted to make the nav bar closer in style to the old beta site / current main site. Adjusted the font weights, the size and position of the search bar, and the nav bar on the right. Also made the `<li>` tags for the curriculum and forum buttons clickable and change styles when hovered over, just like on the main freecodecamp.org site.
Partially solves https://github.com/freeCodeCamp/freeCodeCamp/issues/17266
=> fix: make navbar uniform with main site

src/templates/Challenges/redux/create-question-epic.js
As requested by a forum moderator remove challenge name as title when user click the Ask for Help.
This close [freeCodeCamp#18088](https://github.com/freeCodeCamp/freeCodeCamp/issues/18088#issue-357253301)
=> remove challenge name as title when user click the Ask for Help

src/templates/Challenges/rechallenge/transformers.js, src/templates/Challenges/redux/execute-challenge-epic.js, src/templates/Challenges/utils/build.js, src/templates/Challenges/utils/frame.js
This is a possible fix for #189.  The problem highlighted by #291 was that if both the tests and the test runner interact with console.log, they can clash.  Because of how `proxyLoggerTransformer` rewrote the challenge source, challenges like [Write Reusable JavaScript with Functions](https://github.com/freeCodeCamp/curriculum/blob/ddcc661f425d851f85d13bd47155e2f20e018ed7/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L3060-L3076) would never get their proxy console.logs called.
To avoid this, the test-runner in this PR modifies the frame's console.log directly.  This means that the frame-runner's log is called first, which sends the message to the user log area, then calls test's proxy (if there is one) and that ends calling the native function.
There is a …
=> fix(console): output user logs after running tests

package.json, src/components/OfflineWarning/OfflineWarning.js, src/components/OfflineWarning/index.js, src/components/OfflineWarning/offline-warning.css, src/layouts/index.js, src/redux/app/failed-updates-epic.js, src/redux/app/index.js, src/redux/app/update-complete-epic.js, src/templates/Challenges/redux/completion-epic.js, src/templates/Challenges/redux/current-challenge-epic.js, src/templates/Challenges/utils/ajax-stream.js, src/templates/Challenges/utils/build.js, src/templates/Challenges/utils/index.js, src/templates/Challenges/utils/postUpdate$.js, utils/index.js
This PR adds a feature where, if the browser detects itself to be offline or a request fails, the intended progress update is held in local storage until such time that a successful response from the server is received.
Updates are processed in a staggered manner to reduce the effects on the server; tens (10's) of requests firing at once.
There is a UI element provided to inform a signed in user that there is no response from the server;
=> Feat: Cache updates when the server is unavilable

src/introductions/apis-and-microservices/mongodb-and-mongoose/index.md
This PR is just a duplicate of what was [recently merged](https://github.com/freeCodeCamp/freeCodeCamp/pull/35927) into the `master` branch of the mono repo.  Since mLab is no longer accepting new users, this needs to be merged ASAP into the current production, so campers have valid instructions.
=> fix(learn): updated Introduction to the MongoDB and Mongoose Challenges to use MongoDB Atlas instead of mLab
